kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicloud-operators-test
subjects:
- kind: ServiceAccount
  name: multicloud-operators-test
  namespace: default
roleRef:
  kind: ClusterRole
  name: multicloud-operators-test
  apiGroup: rbac.authorization.k8s.io