apiVersion: app.ibm.com/v1alpha1
kind: AppTest
metadata:
  name: nginx-test
spec: 
  resources:
    - apiVersion: apps/v1
      kind: Deployment
      metadata: 
        name: nginx-ingress-controller
        namespace: default
      cluster: "/"
      desiredStatus:
        availableReplicas: 1
        readyReplicas: 1
        replicas: 1
        updatedReplicas: 1
    - apiVersion: apps/v1
      kind: Deployment
      metadata: 
        name: nginx-ingress-default-backend
        namespace: default
      cluster: "/"
      desiredStatus:
        availableReplicas: 3
        readyReplicas: 3
        replicas: 3
        updatedReplicas: 3



